### PR TITLE
some typos

### PR DESCRIPTION
**Pull request by mickaelandrieu**

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Also, I disagree your conclusion on this article

> To create a new command, we need to:
create a Command class
register the command as a service, with a console.command tag

Register a command class as a service is not required at all, because - as you said - commands are automatically loaded in `Command` folder when suffixed by `Command`.

**Comment by gnugat** [comment]
Thanks for the typo fix!

I try to advocate in the article the systematic usage of a "use case" class and its "handler" service (rather than putting code directly), and injecting services (rather than relying on `ContainerAwareCommand`), which is why in the conclusion I mention this step as required.  Do you think I should add a note explaining it?

**Comment by mickaelandrieu** [comment]
I would say instead:

"To create a new command, we need to create a Command class in the Command folder suffixed by Command. I recommand you to declare command as a service rather than rely on the `ContainerAwareCommand` (why ?)"

What do you think ? The only problem to me here is the verb "need" , but I'm a very bad redactor (and my english is a pity as you can read ^^)

**Comment by gnugat** [comment]
:+1:  I'll update the article later today

**Pull request merged**
