### PR TITLE
Took @kelunik and @bwoebi feedback into account

### PR DESCRIPTION
**Pull request by gnugat**
Hi both of you, this PR tries to take your feedback into account. What do you think?

### CODE REVIEW

**Comment by bwoebi** [comment]
Looks good ;-)

Btw. Seems like a mention in the title doesn't trigger a notification...

**Comment by gnugat** [comment]
Thanks!. Neither does a mention in a commit, from the looks of it.

**Comment by bwoebi** [comment]
I somehow got the mention inside the commit - at the point where you merged it :o

**Comment by kelunik** [comment]
Yup, the merge triggered the ping.

**Pull request merged**
