### PR TITLE
Updated article

### PR DESCRIPTION
**Pull request by mickaelandrieu**
Also, I'm not sure the note FQCN::Method is part of standalone component: can you confirm ?

### CODE REVIEW

**Comment by gnugat** [comment]
Thanks for the typo fix on `staticMethod`.

EventDispatcher uses [call_user_func](https://github.com/symfony/symfony/blob/33c797ee05061538b7a5b4999056fb2362dd7655/src/Symfony/Component/EventDispatcher/EventDispatcher.php#L171), so anything that is considered as a `callable` by PHP will work. This includes:

* the array of class instance and method name notation
* the static method notation

[checkout the examples here](http://php.net/manual/en/language.types.callable.php).

**Comment by mickaelandrieu** [comment]
Ok, thank you for information :) it's important to notice that we need to register the Compiler Pass to be able to deal with services from Symfony Dependency Injection component: have the dependency isn't enough outside of Symfony Framework "metapackage" edition :)

**Comment by gnugat** [comment]
I'd like to avoid talking about `CompilerPass` for now, as we're going to see Dependency Injection in two articles.
I'm not sure we need it in the examples used in the current article: `$service` can contain an instance of any class.

**Comment by mickaelandrieu** [comment]
ok, feel free to close this pr and only quick update for the typo, it's ok (except if you send me a "Gnugat Blog Contributor Badge" sticker ^^).

**Comment by gnugat** [comment]
@pyrech would be flooded with those by now :P

**Comment by pyrech** [comment]
:+1: for a "Gnugat Blog Contributor Badge" :stuck_out_tongue:

**Pull request closed without merging**
