### PR TITLE
Update 2016-07-27-mars-rover-event-sourcing-package.md

### PR DESCRIPTION
**Pull request by nfragnet**

### CODE REVIEW

**Comment by gnugat** [comment]
Hey! The `packages/navigation/src/MarsRover/EventSourcing` files have now been moved to `packages/event-sourcing/src/MarsRover/EventSourcing`, so we no longer need to configure this namespace in the autoloader (adding `mars-rover/event-sourcing` to the `require` section will import this pakage and autoload those classes).

**Comment by nfragnet** [comment]
In fact the problem was the following : 

I was trying to execute tests from `/packages/navigation` and PHPSpec was trying to generate file `MarsRover/Navigation/AnEventHappened`.

The tests passed without problem if I launched the tests from root.

When I added the namespace in `packages/navigation/composer.json`, tests launched from the navigation package directory passed.

**Comment by nfragnet** [comment]
Ok my bad, can't reproduce the issue. I guess I forgot the "require" line in "Event Sourcing package" part.

**Comment by gnugat** [comment]
Sorry about that, if by any chance you can reproduce again the issue could you drop me a line again? Thanks.

**Pull request closed without merging**
